name: Generate Release Tag

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout ðŸ“¦
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Python Semantic Release ðŸš€
      id: release
      uses: python-semantic-release/python-semantic-release@v9.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog: true
        root_options: "-c releaserc.toml -vv"
    - name: Install the latest version of uv ðŸ“¦
      uses: astral-sh/setup-uv@v2
    - name: Build distributions ðŸ“¦
      run: |
        PYFUTURE_TARGET=py312 uv build --wheel
        PYFUTURE_TARGET=py311 uv build --wheel
        PYFUTURE_TARGET=py310 uv build --wheel
    - name: Publish package distributions to GitHub Releases ðŸš€
      if: steps.release.outputs.released == 'true'
      uses: python-semantic-release/publish-action@v9.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
    - name: Publish package distributions to PyPI ðŸš€
      if: steps.release.outputs.released == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}
